version: 0.2

phases:
  pre_build:
    commands:
      - echo pre build ....
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 786766101582.dkr.ecr.ap-southeast-2.amazonaws.com
  build:
    commands:
      - echo DMS --- Build started on `date`
      - echo DMS --- Start npm install .....
      - npm install 
      - echo DMS --- Start npm install .....
      - npm run build
      - echo DMS --- Building the Docker image...
      - docker build -t base-node-ts-ecr .
      - docker tag base-node-ts-ecr:latest 786766101582.dkr.ecr.ap-southeast-2.amazonaws.com/base-node-ts-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 786766101582.dkr.ecr.ap-southeast-2.amazonaws.com/base-node-ts-ecr:latest
      - echo Writing image definitions file...
      - printf '[{"name":"base-node-ts-container","imageUri":786766101582.dkr.ecr.ap-southeast-2.amazonaws.com/base-node-ts-ecr:latest"}]'  > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
